
class MapProvider:
    async def search_places(self, keyword: str, city: str): ...
    async def geocode(self, address: str): ...
    async def calculate_route(self, origin: str, destination: str): ...



